# Routine playbook
- name: Routine playbook
  hosts: localhost
  connection: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
    docker_requirements: [libffi-dev, libssl-dev]
    repo_path: /home/octopus/ansible/
    home_folder: /home/octopus
    www_dest_path: /var/www/html
    giv_tcp_path: /home/octopus/giv_tcp
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  gather_facts: true

  tasks:
    - name: Update the system
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        autoclean: true

    - name: Ensure apt packages are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mosquitto
        - "{{ docker_requirements }}"

    - name: Get Docker Convenience Script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: "{{ home_folder }}get-docker.sh"
        mode: '0755'

    - name: Install Docker
      ansible.builtin.command:
        cmd: sh "{{ home_folder }}get-docker.sh"
        creates: /usr/bin/docker

    - name: Ensure Docker Compose is installed
      ansible.builtin.command:
        cmd: pip install docker-compose
        creates: /usr/local/bin/docker-compose

    - name: Ensure pip packages installed
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      with_items:
        - rpi_ws281x
        - RPi.GPIO
        - flask

    - name: Make octopus user execute docker commands
      ansible.builtin.user:
        name: octopus
        groups: docker
        append: true

    - name: Update Python scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_folder }}"
        mode: "0644"
        owner: octopus
        group: octopus
      with_fileglob:
        - "python_scripts/*.py"

    # - name: Update webserver files
    #   ansible.builtin.copy:
    #     src: "{{ item }}"
    #     dest: "{{ www_dest_path }}"
    #     mode: "0644"
    #     owner: octopus
    #     group: octopus
    #   with_fileglob:
    #     - "{{ repo_path }}/webpages/*"

    - name: Install service file
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: "0644"
        owner: root
        group: root
      with_items:
        - "{{ repo_path }}misc/led.service"
        - "{{ repo_path }}misc/button.service"
        - "{{ repo_path }}misc/ansible.service"

    - name: Check services started
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - led.service
        - button.service
        - ansible.service
        - mosquitto.service

    - name: Blacklist Broadcom audio driver (for WS2812 LEDs)
      # Restart required if this file is not previously present
      ansible.builtin.copy:
        src: "{{ repo_path }}/misc/blacklist-bcm2835.conf"
        dest: /etc/modprobe.d/
        mode: "0644"
        owner: root
        group: root
        force: false

    - name: Checkout giv_tcp repository
      ansible.builtin.git:
        repo: 'https://github.com/britkat1980/giv_tcp.git'
        dest: "{{ giv_tcp_path }}"
        version: main
        update: true
      become: true
      become_user: octopus

    - name: Restart the giv_tcp Docker containers
      community.docker.docker_compose_v2:
        project_src: "{{ giv_tcp_path }}"
        state: restarted
