# Routine playbook
- name: Routine playbook
  hosts: localhost
  connection: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
    repo_path: /home/ansible
    py_dest_path: /home/octopus
    www_dest_path: /var/www/html
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  gather_facts: true

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/octopus
        state: directory
        mode: "0755"

    - name: Update Python scripts
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ py_dest_path }}"
        mode: "0644"
        owner: octopus
        group: octopus
      with_fileglob:
        - "{{ repo_path }}/python_scripts/*.py"

    - name: Update webserver files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ www_dest_path }}"
        mode: "0644"
        owner: octopus
        group: octopus
      with_fileglob:
        - "{{ repo_path }}/webpages/*"
